name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  
          distribution: 'coretto'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Simulate Deployment
        run: |
          if [ $? -eq 0 ]; then
            echo "Desplegado"
          else
            echo "Error en las pruebas. No se puede desplegar."
            exit 1
          fi
